#!/usr/bin/env bash

cd /autograder/source

# Copy the student's code into the autograder directory. Make sure
# student has the right package name in their file and that it's in
# the right place
cp /autograder/submission/Program3.java /autograder/source/src/main/java/com/gradescope/Program3/

# Compile the student's code with autograder code
bash ./compile.sh

# Run the autograder code
bash ./run.sh > /autograder/results/results.json



